// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrlviemoxljumvcjcrvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ybHZpZW1veGxqdW12Y2pjcnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjk3NzYsImV4cCI6MjA2MzkwNTc3Nn0.tqdizOnUKIrO77iTMlBzl0Tmpd-2seui6JpeUBY-D3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);